# Generated by Django 2.2.3 on 2019-08-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='display_name',
            new_name='display_type',
        ),
    ]
