# Generated by Django 2.2.3 on 2019-07-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cintent',
            new_name='content',
        ),
    ]
